ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_provider_fk
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_patient_fk
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT FK_DRUGTREATMENT_ID
ALTER TABLE SURGERYTREATMENT DROP CONSTRAINT FK_SURGERYTREATMENT_ID
ALTER TABLE RADIOLOGYTREATMENT DROP CONSTRAINT FK_RADIOLOGYTREATMENT_ID
ALTER TABLE RADDATE DROP CONSTRAINT FK_RADDATE_radiology_fk
DROP TABLE PATIENT CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE TREATMENT CASCADE
DROP TABLE DRUGTREATMENT CASCADE
DROP TABLE SURGERYTREATMENT CASCADE
DROP TABLE RADIOLOGYTREATMENT CASCADE
DROP TABLE RADDATE CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
